### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by fusionsec** [snoopysecurity/dvws-node#9]
I can connect to dvws-local but after a bit I'm experiencing app crash:

root@kali:~/dvws-node# npm run dvws

> dvws-node@0.0.1 dvws /root/dvws-node
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
XML-RPC server listening on port 9090
API listening at :80, go to http://dvws.local (127.0.0.1)
(node:5771) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/root/dvws-node/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/root/dvws-node/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/root/dvws-node/node_modules/mysql/lib/protocol/Protocol.js:371:10)
    at Connection._handleNetworkError (/root/dvws-node/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
[nodemon] app crashed - waiting for file changes before starting...

Thanks,

**Comment by snoopysecurity** [comment]
Hmmm I am not able to reproduce this on the latest/master version. Do you in what area of the application this error occurs when you are browsing as normal? Or do you get this when you run `npm run dvws`?

**Comment by fusionsec** [comment]
Hi Sam,

The crash occurs while in npm run dvws, but I'm browsing at the same time. 

Also while in Burp when I forward POST changes to dvws, it seems that that connections aren't being made, and I don't get errors. 

Thanks.

**Comment by snoopysecurity** [comment]
I was able to reproduce this issue while using `docker-compose`, hmm I ll try and add a fix later, for now you can build everything from source if it helps https://github.com/snoopysecurity/dvws-node#manual. do let me know if you get the same issue when following the manual processs

**Comment by snoopysecurity** [comment]
Hi @fusionsec, i looked into this issue, it was something to do with the version of mongoose (mongodb) and a bug there. I believe its fixed now on master, can you clone and try to reproduce this bug again?

**Comment by fusionsec** [comment]
Hi Sam,

Thanks for working on this issue, however after reinstalling dvws the crash occurred within 15 mins, and before your change the  
 crashed occurred around 5mins after launching. I'm still getting same error as before.

**Comment by fusionsec** [comment]
Addionally, I'm getting the same error with one new addition being token expiration:

XML-RPC server listening on port 9090
API listening at :80, go to http://dvws.local (127.0.0.1)
(node:4566) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use node --trace-deprecation ... to show where the warning was created)
Error: TokenExpiredError: jwt expired
at validateToken (/root/dvws-node/utils.js:18:15)
at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
at next (/root/dvws-node/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/root/dvws-node/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
at /root/dvws-node/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
at Function.handle (/root/dvws-node/node_modules/express/lib/router/index.js:174:3)
at router (/root/dvws-node/node_modules/express/lib/router/index.js:47:12)
at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/root/dvws-node/node_modules/express/lib/router/index.js:317:13)
at /root/dvws-node/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
at cors (/root/dvws-node/node_modules/cors/lib/index.js:188:7)
Error: TokenExpiredError: jwt expired
at validateToken (/root/dvws-node/utils.js:18:15)
at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
at next (/root/dvws-node/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/root/dvws-node/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
at /root/dvws-node/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
at Function.handle (/root/dvws-node/node_modules/express/lib/router/index.js:174:3)
at router (/root/dvws-node/node_modules/express/lib/router/index.js:47:12)
at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/root/dvws-node/node_modules/express/lib/router/index.js:317:13)
at /root/dvws-node/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
at cors (/root/dvws-node/node_modules/cors/lib/index.js:188:7)
events.js:291
throw er; // Unhandled 'error' event
^

Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
at Connection._handleProtocolError (/root/dvws-node/node_modules/mysql/lib/Connection.js:423:8)
at Protocol.emit (events.js:314:20)
at Protocol._delegateError (/root/dvws-node/node_modules/mysql/lib/protocol/Protocol.js:398:10)
at Protocol.handleNetworkError (/root/dvws-node/node_modules/mysql/lib/protocol/Protocol.js:371:10)
at Connection._handleNetworkError (/root/dvws-node/node_modules/mysql/lib/Connection.js:418:18)
at Socket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
errno: -104,
code: 'ECONNRESET',
syscall: 'read',
fatal: true
}
[nodemon] app crashed - waiting for file changes before starting...

Thanks again for your assistance.

**Comment by snoopysecurity** [comment]
Looked into this again, maybe a mongoose dependency problem or a docker WAIT_HOSTS, have slighted made changes to both on config.

I have added `ignoreExpiration: true` for JWT tokens as well, so the above error shouldn't happen either. Have a try again with docker-compose :)

**Comment by snoopysecurity** [comment]
Closing due to inactivity
